### ISSUE TITLE
Dart Analyzer gives me warnings

### ISSUE THREAD

**Issue by kalismeras61** [aloisdeniel/flutter_sheet_localization#13] opened 2020-02-08 06:50 UTC
Hi,

I just started to using this plugin. But Dart Analyzer give me `Name types using UpperCamelCase.`  error as you know effective dart style  "UpperCamelCase names capitalize the first letter of each word, including the first."

https://dart.dev/guides/language/effective-dart/style

when you create classes the classes name must be combined.

Below example give me error. 
```
class AppLocalizations_Labels_App_Name {
  const AppLocalizations_Labels_App_Name({this.long, this.short});
  final String long;
  final String short;
}
```
Should be like below.

```
class AppLocalizationsLabelsAppName {
  const AppLocalizationsLabelsAppName({this.long, this.short});
  final String long;
  final String short;
}
```

**Comment by aloisdeniel** [comment] 2020-02-08 08:06
You’re right!

The issue is a separator is needed to avoid conflicts ( ‘title.button.text’ and ‘titleButton.text’ would give the same output). Maybe this wouldn’t come so often... Or find a valid separator for Dart analyzer.

**Comment by aloisdeniel** [comment] 2020-11-11 14:24
It should be fixed in latest version.

I added an ignore clause at the beginning of the generated file.

```dart
// ignore_for_file: camel_case_types
```

**Closed by aloisdeniel** 2020-11-11 14:24 UTC
Labels: enhancement

**Comment by frroossst** [comment] 2021-03-22 10:43
Thanks, it was very helpful
